import VersoBlog
open Verso Genre Blog
open Verso.Output Verso.Output.Html

/-- The fleet timelines. The SVGs are regenerated by the `pages` workflow from the database that
https://github.com/TauCetiProject/TauCetiCI rebuilds every three hours (`scripts/ci_stats_graphs.py`); the
committed copies in `static_files/` are fallback snapshots, like the other charts. -/
def fleetGraphs : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/ci-fleet-72h.svg"
         alt="CI jobs running, queued and waiting over the last 72 hours, by runner and kind"/>
    <figcaption>"The last three days in ten-minute bins."</figcaption>
  </figure>
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/ci-fleet-30d.svg"
         alt="CI jobs running, queued and waiting over the last 30 days, by runner and kind"
         loading="lazy"/>
    <figcaption>"The last thirty days in two-hour bins."</figcaption>
  </figure>
}}

/-- One daily chart, full width. -/
def dailyChart (file alt caption : String) : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src={{s!"static/{file}"}} alt={{alt}} loading="lazy"/>
    <figcaption>{{caption}}</figcaption>
  </figure>
}}

def durationGraph : Html := dailyChart "ci-build-duration.svg"
  "Median and 90th-percentile build time per day, by where the build ran"
  "Solid lines are medians, dashed lines 90th percentiles."
def waitGraph : Html := dailyChart "ci-build-wait.svg"
  "Median and 90th-percentile wait for a runner per day, by where the job ran"
  "Solid lines are medians, dashed lines 90th percentiles."
def phasesGraph : Html := dailyChart "ci-build-phases.svg"
  "Mean minutes per successful PR build, stacked by phase"
  "Mean minutes per successful PR build, by phase."
def failuresGraph : Html := dailyChart "ci-failures.svg"
  "Failed PR builds per day by cause, and the failure rate"
  "Failed PR builds by cause; the dashed line is the share of PR builds that failed."
def minutesGraph : Html := dailyChart "ci-runner-minutes.svg"
  "Runner-minutes per day on Namespace and on GitHub-hosted runners"
  "Runner-minutes per day."
def queueGraph : Html := dailyChart "ci-merge-queue.svg"
  "Merge-queue builds per day by outcome, and PRs landed"
  "Merge-queue builds by outcome; the dashed line is PRs landed on main."
def pickerGraph : Html := dailyChart "ci-picker.svg"
  "Share of PR builds run on GitHub-hosted runners per day"
  "Share of PR builds the runner picker sent to GitHub-hosted runners."

#doc (Page) "CI" =>

Where does Tau Ceti's continuous integration run, and how long does it wait? Every pull request
is built in a sandbox, on one of two kinds of runner. GitHub-hosted runners cost nothing for a
public repository, but the organisation may run only twenty GitHub-hosted jobs at once, across
all of its repositories. Namespace runners are faster and have no such cap, but every minute is
paid for. So a pull-request build takes a GitHub runner while one is free and overflows to
Namespace when they are all taken; the merge queue, which every pull request must pass to land,
always builds on Namespace.

The timeline below has three panels on one time axis. The top panel shows how many jobs were
running, averaged over each bin and stacked by runner and kind, against the twenty-job cap on
GitHub-hosted jobs. "Other GitHub jobs" are mostly the label, notification and merge-bot jobs
that run on every pull-request event; they are brief but numerous, and they compete with builds
for the same twenty slots. Ticks below the panel mark pull-request builds that the runner picker
sent to Namespace, and dotted lines mark changes to the CI configuration. The middle panel shows
the most jobs waiting for a runner at any moment in each bin. The bottom panel shows the longest
wait for a runner among jobs that started in the previous thirty minutes (or the previous bin,
when bins are longer), for builds and for other jobs separately.

:::blob fleetGraphs
:::

# Day by day

The charts below give one point per complete UTC day, for up to the last ninety days.

How long does a build take, and how long does it wait before starting? A pull-request build
compiles only what the pull request changed, restoring everything else from the artifact cache, then
runs the audits and lints over the whole library. Namespace machines have eight cores where
GitHub-hosted runners have four, so the same build is faster there.

:::blob durationGraph
:::

:::blob waitGraph
:::

Where does a build's time go? The build, the audits and the two lints run in one sandboxed step;
since the build began recording its own phases, that step is split into them. Before then it
appears as one block.

:::blob phasesGraph
:::

Why do builds fail? Each failed pull-request build is classified by the step that failed and the
error lines it printed: a Lean error, one of the lints, one of the audits, a policy check (scope,
size, pins), or an infrastructure fault such as a cache download. Infrastructure faults are the
ones a re-run fixes.

:::blob failuresGraph
:::

What does it cost? Namespace bills every minute; GitHub-hosted minutes cost nothing for a public
repository. A cancelled build is one a newer push to the same pull request replaced before it
finished, so its minutes bought nothing.

:::blob minutesGraph
:::

:::blob pickerGraph
:::

How is the merge queue doing? The queue builds each pull request together with those ahead of it,
and lands them only if that combined build passes. A failed merge-queue build sends its pull request
back, and the ones behind it are rebuilt.

:::blob queueGraph
:::

# Where the data comes from

The data comes from [TauCetiCI](https://github.com/TauCetiProject/TauCetiCI), which records
every GitHub Actions run in the organisation: the commits each build tested, the runner, the
queue and run times of its jobs, and why failed builds failed. Its database is published as a
release there for anyone who wants to ask their own questions. The charts end where that record
is complete, which can be a few hours behind the present.

Builds are recorded job by job. The label, notification and merge-bot workflows run thousands of
times a day, so for them only one run in four is recorded job by job, and each of those stands
for the unrecorded runs of its workflow in the same hour. Their share of the running and queued
panels is therefore an estimate, and their longest waits come from the sample. Before hourly
collection began, none of their runs were recorded job by job; there the running panel places an
estimated job at the end of each run, and the queue and wait panels leave those runs out.
