import VersoBlog
open Verso Genre Blog
open Verso.Output Verso.Output.Html

/-- The fleet timelines. The SVGs are regenerated by the `pages` workflow from the database that
https://github.com/TauCetiProject/TauCetiCI rebuilds daily (`scripts/ci_stats_graphs.py`); the
committed copies in `static_files/` are fallback snapshots, like the other charts. -/
def fleetGraphs : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/ci-fleet-72h.svg"
         alt="CI jobs running, queued and waiting over the last 72 hours, by runner and kind"/>
    <figcaption>"The last three days in ten-minute bins."</figcaption>
  </figure>
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/ci-fleet-30d.svg"
         alt="CI jobs running, queued and waiting over the last 30 days, by runner and kind"
         loading="lazy"/>
    <figcaption>"The last thirty days in two-hour bins."</figcaption>
  </figure>
}}

#doc (Page) "CI" =>

Where does Tau Ceti's continuous integration run, and how long does it wait? Every pull request
is built in a sandbox, on one of two kinds of runner. GitHub-hosted runners cost nothing for a
public repository, but the organisation may run only twenty GitHub-hosted jobs at once, across
all of its repositories. Namespace runners are faster and have no such cap, but every minute is
paid for. So a pull-request build takes a GitHub runner while one is free and overflows to
Namespace when they are all taken; the merge queue, which every pull request must pass to land,
always builds on Namespace.

The timeline below has three panels on one time axis. The top panel shows how many jobs were
running, averaged over each bin and stacked by runner and kind, against the twenty-job cap on
GitHub-hosted jobs. "Short jobs" are the label, notification and merge-bot jobs that run on
every pull-request event; they are brief but numerous, and they compete with builds for the
same twenty slots. Ticks below the panel mark pull-request builds that the runner picker sent to
Namespace, and dotted lines mark changes to the CI configuration. The middle panel shows the
most jobs waiting for a runner at any moment in each bin. The bottom panel shows the longest
wait for a runner among jobs that started in the previous thirty minutes, for builds and for
short jobs separately.

:::blob fleetGraphs
:::

The data comes from [TauCetiCI](https://github.com/TauCetiProject/TauCetiCI), which records
every GitHub Actions run in the organisation: the commits each build tested, the runner, the
queue and run times of every job, and why failed builds failed. Its database is published as a
release there for anyone who wants to ask their own questions. For runs recorded before hourly
collection began, the short jobs' timings are estimated from their runs, so those periods show
how busy the runners were but not how long short jobs waited.
