/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import TauCeti.Algebra.Order.Ring.Ordering.Extension
public import Mathlib.Algebra.Order.Field.Basic
public import Mathlib.Algebra.Order.Hom.Monoid
public import Mathlib.Algebra.QuadraticAlgebra.Basic

/-! # Preserving an order under field extension

The cone generated by nonnegative base elements and extension-field squares
describes precisely the obstruction to extending an order. For a positive
quadratic extension, its scalar coordinate proves that this cone is proper.
-/

public section

namespace TauCeti.RealClosure

variable {K L : Type*} [Field K] [LinearOrder K] [IsStrictOrderedRing K]

section CommRing

variable [CommRing L]

/-- Nonnegative scalar multiples of squares in an extension. -/
@[expose] def weightedSquares (f : K →+* L) : Set L :=
  {x | ∃ a : K, 0 ≤ a ∧ ∃ y : L, x = f a * y ^ 2}

private theorem weightedSquares_mul (f : K →+* L) {x y : L}
    (hx : x ∈ weightedSquares f) (hy : y ∈ weightedSquares f) :
    x * y ∈ weightedSquares f := by
  obtain ⟨a, ha, u, rfl⟩ := hx
  obtain ⟨b, hb, v, rfl⟩ := hy
  exact ⟨a * b, mul_nonneg ha hb, u * v, by rw [map_mul]; ring⟩

/-- Finite sums of nonnegative scalar multiples of squares. -/
def extensionCone (f : K →+* L) : Subsemiring L where
  __ := AddSubmonoid.closure (weightedSquares f)
  one_mem' := AddSubmonoid.subset_closure ⟨1, zero_le_one, 1, by simp⟩
  mul_mem' {x y} hx hy := by
    induction hx using AddSubmonoid.closure_induction with
    | mem x hx =>
      induction hy using AddSubmonoid.closure_induction with
      | mem y hy => exact AddSubmonoid.subset_closure (weightedSquares_mul f hx hy)
      | zero => simp
      | add y z _ _ hy hz => simpa [mul_add] using add_mem hy hz
    | zero => simp
    | add x z _ _ hx hz => simpa [add_mul] using add_mem hx hz

/-- A generating weighted square belongs to the extension cone. -/
theorem subset_extensionCone (f : K →+* L) {x : L} (hx : x ∈ weightedSquares f) :
    x ∈ extensionCone f := AddSubmonoid.subset_closure hx

/-- Induction on finite sums of generating weighted squares. -/
@[elab_as_elim] theorem extensionCone_induction (f : K →+* L)
    {motive : (x : L) → x ∈ extensionCone f → Prop}
    (mem : ∀ x (hx : x ∈ weightedSquares f), motive x (subset_extensionCone f hx))
    (zero : motive 0 (zero_mem _))
    (add : ∀ x y hx hy, motive x hx → motive y hy → motive (x + y) (add_mem hx hy))
    {x : L} (hx : x ∈ extensionCone f) : motive x hx :=
  AddSubmonoid.closure_induction mem zero add hx

theorem extensionCone.mul_self_mem (f : K →+* L) (x : L) : x * x ∈ extensionCone f :=
  subset_extensionCone f ⟨1, zero_le_one, x, by simp [pow_two]⟩

theorem nonneg_mem_extensionCone (f : K →+* L) {x : K} (hx : 0 ≤ x) :
    f x ∈ extensionCone f :=
  subset_extensionCone f ⟨x, hx, 1, by simp⟩

/-- A linear functional nonnegative on the generating weighted squares is
nonnegative on the entire extension cone. -/
theorem extensionCone.map_nonneg (f : K →+* L) (g : L →+ K)
    (hg : ∀ a : K, 0 ≤ a → ∀ y : L, 0 ≤ g (f a * y ^ 2))
    {x : L} (hx : x ∈ extensionCone f) : 0 ≤ g x := by
  induction hx using extensionCone_induction f with
  | mem x hx =>
    obtain ⟨a, ha, y, rfl⟩ := hx
    exact hg a ha y
  | zero => simp
  | add x y _ _ hx hy => simpa only [map_add] using add_nonneg hx hy

/-- Every element of the generated cone is nonnegative in any order extending
the base order. -/
theorem nonneg_of_mem_extensionCone [LinearOrder L] [IsStrictOrderedRing L]
    (f : K →+* L) (hf : Monotone f) {x : L} (hx : x ∈ extensionCone f) : 0 ≤ x := by
  induction hx using extensionCone_induction f with
  | mem x hx =>
    obtain ⟨a, ha, y, rfl⟩ := hx
    exact mul_nonneg (by simpa only [map_zero] using hf ha) (sq_nonneg y)
  | zero => exact le_rfl
  | add x y _ _ hx hy => exact add_nonneg hx hy

end CommRing

section Field

variable [Field L]

/-- The order of the base field extends whenever its generated cone is proper. -/
theorem exists_order_extension (f : K →+* L) (h : -1 ∉ extensionCone f) :
    ∃ o : LinearOrder L, letI := o
      IsStrictOrderedRing L ∧ StrictMono f := by
  let P : RingPreordering L :=
    { extensionCone f with
      mem_of_isSquare' := by
        rintro x ⟨y, rfl⟩
        exact extensionCone.mul_self_mem f y
      neg_one_notMem' := h }
  obtain ⟨o, ho, hP⟩ := RingPreordering.exists_linearOrder P
  let := o
  have := ho
  refine ⟨o, ho, ?_⟩
  exact ((monotone_iff_map_nonneg f).mpr fun x hx =>
    hP _ (nonneg_mem_extensionCone f hx)).strictMono_of_injective f.injective

end Field

section Quadratic

variable {a : K}

/-- Adjoining a square root of a nonnegative element does not force a sum of weighted
squares to equal `-1`. -/
theorem extensionCone.neg_one_notMem_quadratic (ha : 0 ≤ a) :
    -1 ∉ extensionCone (algebraMap K (QuadraticAlgebra K a 0)) := by
  intro h
  have hnonneg := extensionCone.map_nonneg (algebraMap K (QuadraticAlgebra K a 0))
    (QuadraticAlgebra.reₗ (R := K) (a := a) (b := 0)).toAddMonoidHom (fun b hb y => ?_) h
  · exact (not_le_of_gt zero_lt_one) (by simpa [QuadraticAlgebra.re_one] using hnonneg)
  · simp only [LinearMap.toAddMonoidHom_coe, QuadraticAlgebra.reₗ_apply]
    simp only [pow_two, QuadraticAlgebra.re_mul, QuadraticAlgebra.algebraMap_re,
      QuadraticAlgebra.algebraMap_im, zero_mul, mul_zero, add_zero]
    simpa only [mul_assoc] using
      mul_nonneg hb (add_nonneg (mul_self_nonneg y.re) (mul_nonneg ha (mul_self_nonneg y.im)))

/-- A nonnegative nonsquare can be adjoined while preserving the base ordering.
Nonsquareness excludes zero, so the radicand is necessarily positive. -/
theorem exists_quadratic_order (ha : 0 ≤ a) [Fact (¬ IsSquare a)] :
    ∃ o : LinearOrder (QuadraticAlgebra K a 0), letI := o
      IsStrictOrderedRing (QuadraticAlgebra K a 0) ∧
        StrictMono (algebraMap K (QuadraticAlgebra K a 0)) :=
  exists_order_extension _ (extensionCone.neg_one_notMem_quadratic ha)

end Quadratic

end TauCeti.RealClosure
