/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import TauCeti.FieldTheory.RealClosure.Ordering
public import Mathlib.Algebra.Order.Field.Basic
public import Mathlib.Algebra.QuadraticAlgebra.Basic

/-! # Preserving an order under field extension

The cone generated by nonnegative base elements and extension-field squares
describes precisely the obstruction to extending an order. For a positive
quadratic extension, its scalar coordinate proves that this cone is proper.
-/

@[expose] public section

namespace RealClosure

variable {K L : Type*} [Field K] [LinearOrder K] [IsStrictOrderedRing K]

section CommRing

variable [CommRing L]

/-- Nonnegative scalar multiples of squares in an extension. -/
def weightedSquares (f : K →+* L) : Set L :=
  {x | ∃ a : K, 0 ≤ a ∧ ∃ y : L, x = f a * y ^ 2}

private theorem weightedSquares_mul (f : K →+* L) {x y : L}
    (hx : x ∈ weightedSquares f) (hy : y ∈ weightedSquares f) :
    x * y ∈ weightedSquares f := by
  obtain ⟨a, ha, u, rfl⟩ := hx
  obtain ⟨b, hb, v, rfl⟩ := hy
  exact ⟨a * b, mul_nonneg ha hb, u * v, by rw [map_mul]; ring⟩

/-- Finite sums of nonnegative scalar multiples of squares. -/
def extensionCone (f : K →+* L) : Subsemiring L where
  __ := AddSubmonoid.closure (weightedSquares f)
  one_mem' := AddSubmonoid.subset_closure ⟨1, zero_le_one, 1, by simp⟩
  mul_mem' {x y} hx hy := by
    induction hx using AddSubmonoid.closure_induction with
    | mem x hx =>
      induction hy using AddSubmonoid.closure_induction with
      | mem y hy => exact AddSubmonoid.subset_closure (weightedSquares_mul f hx hy)
      | zero => simp
      | add y z _ _ hy hz => simpa [mul_add] using add_mem hy hz
    | zero => simp
    | add x z _ _ hx hz => simpa [add_mul] using add_mem hx hz

theorem square_mem_extensionCone (f : K →+* L) (x : L) : x * x ∈ extensionCone f :=
  AddSubmonoid.subset_closure ⟨1, zero_le_one, x, by simp [pow_two]⟩

theorem nonneg_mem_extensionCone (f : K →+* L) {x : K} (hx : 0 ≤ x) :
    f x ∈ extensionCone f :=
  AddSubmonoid.subset_closure ⟨x, hx, 1, by simp⟩

/-- A linear functional nonnegative on the generating weighted squares is
nonnegative on the entire extension cone. -/
theorem extensionCone_nonneg (f : K →+* L) (g : L →+ K)
    (hg : ∀ a : K, 0 ≤ a → ∀ y : L, 0 ≤ g (f a * y ^ 2))
    {x : L} (hx : x ∈ extensionCone f) : 0 ≤ g x := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨a, ha, y, rfl⟩ := hx
    exact hg a ha y
  | zero => simp
  | add x y _ _ hx hy => simpa only [map_add] using add_nonneg hx hy

end CommRing

section Field

variable [Field L]

/-- Every element of the generated cone is nonnegative in any order extending
the base order. -/
theorem nonneg_of_mem_extensionCone [LinearOrder L] [IsStrictOrderedRing L]
    (f : K →+* L) (hf : StrictMono f) {x : L} (hx : x ∈ extensionCone f) : 0 ≤ x := by
  induction hx using AddSubmonoid.closure_induction with
  | mem x hx =>
    obtain ⟨a, ha, y, rfl⟩ := hx
    exact mul_nonneg (by simpa only [map_zero] using hf.monotone ha) (sq_nonneg y)
  | zero => exact le_rfl
  | add x y _ _ hx hy => exact add_nonneg hx hy

/-- The order of the base field extends whenever its generated cone is proper. -/
theorem exists_order_extension (f : K →+* L) (h : -1 ∉ extensionCone f) :
    ∃ o : LinearOrder L, letI := o
      IsStrictOrderedRing L ∧ StrictMono f := by
  let P : RingPreordering L :=
    { extensionCone f with
      mem_of_isSquare' := by
        rintro x ⟨y, rfl⟩
        exact square_mem_extensionCone f y
      neg_one_notMem' := h }
  obtain ⟨o, ho, hP⟩ := Preordering.exists_linearOrder P
  let := o
  have := ho
  refine ⟨o, ho, ?_⟩
  intro a b hab
  have hn : 0 ≤ f (b - a) := hP _ (nonneg_mem_extensionCone f (sub_nonneg.mpr hab.le))
  have hz : f (b - a) ≠ 0 := (map_ne_zero f).mpr (sub_ne_zero.mpr hab.ne')
  simpa only [map_sub, sub_pos] using lt_of_le_of_ne hn hz.symm

end Field

section Quadratic

variable {a : K}

/-- Positive quadratic adjunction does not force a sum of weighted squares to
equal `-1`; its scalar coordinate is nonnegative. -/
theorem quadratic_cone_proper (ha : 0 ≤ a) :
    -1 ∉ extensionCone (algebraMap K (QuadraticAlgebra K a 0)) := by
  intro h
  have hnonneg := extensionCone_nonneg (algebraMap K (QuadraticAlgebra K a 0))
    (QuadraticAlgebra.reₗ (R := K) (a := a) (b := 0)).toAddMonoidHom (fun b hb y => ?_) h
  · exact (not_le_of_gt zero_lt_one) (by simpa [QuadraticAlgebra.re_one] using hnonneg)
  · change 0 ≤ (algebraMap K (QuadraticAlgebra K a 0) b * y ^ 2).re
    simp only [pow_two, QuadraticAlgebra.re_mul, QuadraticAlgebra.algebraMap_re,
      QuadraticAlgebra.algebraMap_im, zero_mul, mul_zero, add_zero]
    simpa only [mul_assoc] using
      mul_nonneg hb (add_nonneg (mul_self_nonneg y.re) (mul_nonneg ha (mul_self_nonneg y.im)))

/-- A nonnegative nonsquare can be adjoined while preserving the base ordering.
Nonsquareness excludes zero, so the radicand is necessarily positive. -/
theorem exists_quadratic_order (ha : 0 ≤ a) [Fact (¬ IsSquare a)] :
    ∃ o : LinearOrder (QuadraticAlgebra K a 0), letI := o
      IsStrictOrderedRing (QuadraticAlgebra K a 0) ∧
        StrictMono (algebraMap K (QuadraticAlgebra K a 0)) :=
  exists_order_extension _ (quadratic_cone_proper ha)

end Quadratic

end RealClosure
